"""isemployee

Revision ID: 2cd8d6b836fa
Revises: ee1b9f7ae371
Create Date: 2022-03-06 10:41:21.840437

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2cd8d6b836fa'
down_revision = 'ee1b9f7ae371'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vartotojas', sa.Column('is_employee', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vartotojas', 'is_employee')
    # ### end Alembic commands ###
