"""isadmin

Revision ID: 4523c32e15b5
Revises: e50aa479e50d
Create Date: 2022-03-03 11:33:39.360051

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4523c32e15b5'
down_revision = 'e50aa479e50d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vartotojas', sa.Column('is_admin', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vartotojas', 'is_admin')
    # ### end Alembic commands ###
