"""gedimo_kaina

Revision ID: 5c32c166b1a2
Revises: b6797093292d
Create Date: 2022-03-07 10:34:26.763996

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c32c166b1a2'
down_revision = 'b6797093292d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gedimas', sa.Column('Gedimo kaina', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('gedimas', 'Gedimo kaina')
    # ### end Alembic commands ###
