"""gedimo_busena

Revision ID: b6797093292d
Revises: 2cd8d6b836fa
Create Date: 2022-03-06 17:30:03.929387

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b6797093292d'
down_revision = '2cd8d6b836fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gedimas', sa.Column('Gedimo būsena', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('gedimas', 'Gedimo būsena')
    # ### end Alembic commands ###
