"""gedimo_numeris

Revision ID: 1c27541bdd0c
Revises: 5c32c166b1a2
Create Date: 2022-03-09 12:29:59.996580

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c27541bdd0c'
down_revision = '5c32c166b1a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gedimas', sa.Column('gedimo_numeris', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('gedimas', 'gedimo_numeris')
    # ### end Alembic commands ###
