"""pirmas

Revision ID: b970c02abff8
Revises: 
Create Date: 2022-02-26 15:50:51.007873

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b970c02abff8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vartotojas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Vartotojo vardas', sa.String(length=200), nullable=False),
    sa.Column('El.paštas', sa.String(length=200), nullable=False),
    sa.Column('Slaptažodis', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('El.paštas'),
    sa.UniqueConstraint('Vartotojo vardas')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vartotojas')
    # ### end Alembic commands ###
