"""irasai

Revision ID: bde72a12434f
Revises: b970c02abff8
Create Date: 2022-02-27 18:33:52.487587

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bde72a12434f'
down_revision = 'b970c02abff8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('irasas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Sukurta', sa.DateTime(), nullable=True),
    sa.Column('Modelis', sa.String(length=200), nullable=False),
    sa.Column('Markė', sa.String(length=200), nullable=False),
    sa.Column('Metai', sa.Integer(), nullable=False),
    sa.Column('Variklis', sa.String(length=200), nullable=False),
    sa.Column('Valstybinis numeris', sa.String(length=200), nullable=False),
    sa.Column('VIN', sa.String(length=17), nullable=False),
    sa.Column('vartotojas_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['vartotojas_id'], ['vartotojas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('irasas')
    # ### end Alembic commands ###
