"""carsukurta

Revision ID: ee1b9f7ae371
Revises: 4523c32e15b5
Create Date: 2022-03-03 14:32:14.511511

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee1b9f7ae371'
down_revision = '4523c32e15b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gedimas', sa.Column('Sukurta', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('gedimas', 'Sukurta')
    # ### end Alembic commands ###
